#!/bin/sh

declare_wait_run(){
	echo press enter to run $@
	read $_var
	$@
}

echo no config arg example
declare_wait_run purs-nix run -s script.clistate lock -i 0 -p 1

echo no config file example
declare_wait_run purs-nix run -c bad_path -s script.clistate lock -i 0 -p 1

echo bad config file example
declare_wait_run purs-nix run -c badWalletCfg -s script.clistate lock -i 0 -p 1

echo no state arg example
declare_wait_run purs-nix run -c testWalletCfg lock -i 0 -p 1

echo no state file on inc example
declare_wait_run purs-nix run -c testWalletCfg -s bad_path inc

echo yes state file on lock
declare_wait_run purs-nix run -c testWalletCfg -s badState lock -i 0 -p 1

echo bad state file on inc example
declare_wait_run purs-nix run -c badWalletCfg -s badState inc
echo this error isn't great but you shouldn't be hand writing state files anyway

echo Finishe error examples
